# Generated by Django 6.0.2 on 2026-03-16 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: AUC-ROC, RMSE, Accuracy, F1-Score', max_length=100, unique=True)),
                ('descripcion_metrica', models.TextField(blank=True, help_text='Breve explicación de qué mide esta métrica')),
            ],
        ),
        migrations.CreateModel(
            name='StackProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('valor_objetivo', models.CharField(blank=True, help_text='Ej: 0.92, 15%, etc.', max_length=100, null=True)),
                ('fecha_proyecto', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('descripcion', models.TextField()),
                ('url_github', models.URLField(blank=True, max_length=255)),
                ('url_demo', models.URLField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.categoriaproyecto')),
                ('tipo_objetivo', models.ForeignKey(blank=True, help_text='Selecciona la métrica principal del proyecto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.metricaobjetivo')),
                ('stack', models.ManyToManyField(related_name='proyectos', to='proyectos.stackproyecto')),
            ],
            options={
                'ordering': ['-fecha_proyecto'],
            },
        ),
    ]
