# Generated by Django 6.0.2 on 2026-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del sector, ej: Finanzas, Salud, Retail, etc.')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaproyecto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve de la categoría, ej: Visión por Computadora, Procesamiento de Lenguaje Natural, etc.'),
        ),
        migrations.AddField(
            model_name='stackproyecto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del stack tecnológico, ej: Python, TensorFlow, AWS, etc.'),
        ),
    ]
