# Generated by Django 6.0.2 on 2026-03-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_sectorproyecto_categoriaproyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.sectorproyecto'),
        ),
    ]
