# Generated by Django 6.0.2 on 2026-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='portada',
            field=models.BooleanField(default=False),
        ),
    ]
