# Generated by Django 6.0.2 on 2026-03-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_proyecto_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL de la imagen del proyecto', max_length=500, null=True),
        ),
    ]
