# Generated by Django 6.0.2 on 2026-04-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_proyecto_contenido_alter_proyecto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='url_notebook',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
