# Generated by Django 6.0.2 on 2026-03-18 09:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('contenido', models.TextField(help_text='Cuerpo del artículo en formato Markdown.')),
                ('extracto', models.TextField(blank=True, help_text='Resumen corto para las tarjetas de presentación.', max_length=500)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen destacada del post.', max_length=500, null=True)),
                ('publicado', models.BooleanField(default=False, verbose_name='¿Está publicado?')),
                ('portada', models.BooleanField(default=False, verbose_name='¿Mostrar en la Home?')),
                ('tiempo_lectura', models.PositiveIntegerField(default=5, help_text='Minutos estimados de lectura.')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='categoriablog',
            options={'verbose_name': 'Categoría de Blog', 'verbose_name_plural': 'Categorías del Blog'},
        ),
        migrations.AddField(
            model_name='categoriablog',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción de la categoría.'),
        ),
        migrations.AddField(
            model_name='categoriablog',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriablog',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoriablog'),
        ),
    ]
